###
POST http://localhost:8084/cuenta/register-cuenta
Content-Type: application/json

{
  "numeroCuenta": "0002255",
  "tipoCuenta": "Ahorros",
  "saldoInicial": 600,
  "estado": true,
  "clienteId": 1
}

###
POST http://localhost:8084/movimientos/register-movimientos
Content-Type: application/json

{
  "fecha": "10/02/2022",
  "tipoMovimiento": "Corriente",
  "valor": 20,
  "saldo": 60,
  "cuenta": {
    "cuenta_id": 1
  }
}